'use client';

import { useState, useEffect } from 'react';
import { CartItem } from '@/context/cartContext';
import { Clock, User, Search, X, Trash2 } from 'lucide-react';

interface HeldOrder {
  id: string;
  customerName: string;
  customerId?: number;
  cartItems: CartItem[];
  total: number;
  timestamp: number;
  isAutoGenerated: boolean;
}

interface Customer {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
}

interface HoldOrderManagerProps {
  currentCart: CartItem[];
  currentTotal: number;
  onHoldComplete: () => void;
  onResumeOrder: (items: CartItem[]) => void;
}

const HOLD_ORDERS_KEY = 'held_orders';
const AUTO_CLEANUP_HOURS = 4;

export default function HoldOrderManager({
  currentCart,
  currentTotal,
  onHoldComplete,
  onResumeOrder,
}: HoldOrderManagerProps) {
  const [heldOrders, setHeldOrders] = useState<HeldOrder[]>([]);
  const [showHoldModal, setShowHoldModal] = useState(false);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [customerSearch, setCustomerSearch] = useState('');
  const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null);
  const [loading, setLoading] = useState(false);

  // Load held orders from localStorage
  useEffect(() => {
    loadHeldOrders();
    fetchCustomers();
  }, []);

  // Auto-cleanup old orders every minute
  useEffect(() => {
    const interval = setInterval(() => {
      cleanupOldOrders();
    }, 60000); // Run every minute

    return () => clearInterval(interval);
  }, []);

  const loadHeldOrders = () => {
    try {
      const saved = localStorage.getItem(HOLD_ORDERS_KEY);
      if (saved) {
        const orders: HeldOrder[] = JSON.parse(saved);
        setHeldOrders(orders);
        cleanupOldOrders(orders);
      }
    } catch (err) {
      console.error('Failed to load held orders:', err);
    }
  };

  const saveHeldOrders = (orders: HeldOrder[]) => {
    localStorage.setItem(HOLD_ORDERS_KEY, JSON.stringify(orders));
    setHeldOrders(orders);
  };

  const cleanupOldOrders = (orders: HeldOrder[] = heldOrders) => {
    const cutoffTime = Date.now() - (AUTO_CLEANUP_HOURS * 60 * 60 * 1000);
    const filtered = orders.filter(order => order.timestamp > cutoffTime);

    if (filtered.length < orders.length) {
      console.log(`🧹 Cleaned up ${orders.length - filtered.length} old held orders`);
      saveHeldOrders(filtered);
    }
  };

  const fetchCustomers = async () => {
    try {
      const res = await fetch('/api/admin/customers');
      if (res.ok) {
        const data = await res.json();
        setCustomers(Array.isArray(data) ? data : []);
      }
    } catch (err) {
      console.error('Failed to fetch customers:', err);
    }
  };

  const generateHoldTag = (): string => {
    const now = new Date();
    const dateStr = now.toISOString().slice(2, 10).replace(/-/g, ''); // YYMMDD

    // Find highest counter for today
    const todayPrefix = dateStr;
    const todayOrders = heldOrders.filter(o =>
      o.isAutoGenerated && o.customerName.startsWith(todayPrefix)
    );

    let maxCounter = 0;
    todayOrders.forEach(o => {
      const match = o.customerName.match(/_H(\d+)$/);
      if (match) {
        const counter = parseInt(match[1]);
        if (counter > maxCounter) maxCounter = counter;
      }
    });

    const nextCounter = maxCounter + 1;
    return `${dateStr}_H${String(nextCounter).padStart(3, '0')}`;
  };

  const handleHoldOrder = () => {
    if (currentCart.length === 0) {
      alert('Cannot hold an empty cart');
      return;
    }

    const customerName = selectedCustomer
      ? `${selectedCustomer.first_name} ${selectedCustomer.last_name}`
      : generateHoldTag();

    const newHeldOrder: HeldOrder = {
      id: `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      customerName,
      customerId: selectedCustomer?.id,
      cartItems: [...currentCart],
      total: currentTotal,
      timestamp: Date.now(),
      isAutoGenerated: !selectedCustomer,
    };

    const updatedOrders = [...heldOrders, newHeldOrder];
    saveHeldOrders(updatedOrders);

    setShowHoldModal(false);
    setSelectedCustomer(null);
    setCustomerSearch('');
    onHoldComplete();

    console.log(`📦 Held order for: ${customerName}`);
  };

  const handleResumeOrder = (order: HeldOrder) => {
    const updatedOrders = heldOrders.filter(o => o.id !== order.id);
    saveHeldOrders(updatedOrders);
    onResumeOrder(order.cartItems);
    console.log(`▶️  Resumed order for: ${order.customerName}`);
  };

  const handleDeleteOrder = (orderId: string) => {
    if (!confirm('Delete this held order?')) return;

    const updatedOrders = heldOrders.filter(o => o.id !== orderId);
    saveHeldOrders(updatedOrders);
    console.log(`🗑️  Deleted held order`);
  };

  const getElapsedTime = (timestamp: number): string => {
    const elapsedMs = Date.now() - timestamp;
    const elapsedMinutes = Math.floor(elapsedMs / 60000);

    if (elapsedMinutes < 60) {
      return `${elapsedMinutes}m ago`;
    } else {
      const hours = Math.floor(elapsedMinutes / 60);
      const mins = elapsedMinutes % 60;
      return `${hours}h ${mins}m ago`;
    }
  };

  const filteredCustomers = customers.filter(c =>
    c.first_name.toLowerCase().includes(customerSearch.toLowerCase()) ||
    c.last_name.toLowerCase().includes(customerSearch.toLowerCase()) ||
    c.email.toLowerCase().includes(customerSearch.toLowerCase()) ||
    c.phone?.includes(customerSearch)
  );

  return (
    <>
      {/* Hold Order Button */}
      {currentCart.length > 0 && (
        <button
          onClick={() => setShowHoldModal(true)}
          className="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition font-semibold flex items-center justify-center gap-2 mb-3"
        >
          <Clock className="w-5 h-5" />
          Hold Order
        </button>
      )}

      {/* Held Orders List */}
      {heldOrders.length > 0 && (
        <div className="bg-white rounded-lg shadow p-4 mb-4">
          <h3 className="font-semibold text-gray-700 mb-3 flex items-center gap-2">
            <Clock className="w-5 h-5" />
            Held Orders ({heldOrders.length})
          </h3>
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {heldOrders.map((order) => (
              <div
                key={order.id}
                className="flex items-center justify-between p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition"
              >
                <button
                  onClick={() => handleResumeOrder(order)}
                  className="flex-1 text-left"
                >
                  <div className="font-medium text-gray-800">
                    {order.customerName}
                  </div>
                  <div className="text-sm text-gray-500">
                    RM {order.total.toFixed(2)} • {getElapsedTime(order.timestamp)}
                  </div>
                </button>
                <button
                  onClick={() => handleDeleteOrder(order.id)}
                  className="p-2 text-red-600 hover:bg-red-100 rounded-lg transition"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Hold Order Modal */}
      {showHoldModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            {/* Header */}
            <div className="sticky top-0 bg-white border-b p-4 flex items-center justify-between">
              <h2 className="text-xl font-bold">Hold Order</h2>
              <button
                onClick={() => {
                  setShowHoldModal(false);
                  setSelectedCustomer(null);
                  setCustomerSearch('');
                }}
                className="p-2 hover:bg-gray-100 rounded-full transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6">
              <p className="text-gray-600 mb-4">
                Select a customer or leave blank to auto-generate a hold tag
              </p>

              {/* Customer Search */}
              <div className="mb-4">
                <div className="relative mb-3">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="text"
                    placeholder="Search customers by name, email, or phone..."
                    value={customerSearch}
                    onChange={(e) => setCustomerSearch(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>

                {/* Selected Customer Display */}
                {selectedCustomer && (
                  <div className="mb-3 p-3 bg-blue-50 rounded-lg flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <User className="w-5 h-5 text-blue-600" />
                      <div>
                        <p className="font-medium text-blue-900">
                          {selectedCustomer.first_name} {selectedCustomer.last_name}
                        </p>
                        <p className="text-sm text-blue-600">{selectedCustomer.email}</p>
                      </div>
                    </div>
                    <button
                      onClick={() => setSelectedCustomer(null)}
                      className="text-blue-600 hover:text-blue-800 text-sm font-medium"
                    >
                      Clear
                    </button>
                  </div>
                )}

                {/* Customer List */}
                {!selectedCustomer && customerSearch && (
                  <div className="max-h-64 overflow-y-auto border rounded-lg">
                    {filteredCustomers.length === 0 ? (
                      <div className="p-4 text-center text-gray-500">
                        No customers found
                      </div>
                    ) : (
                      <div className="divide-y">
                        {filteredCustomers.map((customer) => (
                          <button
                            key={customer.id}
                            onClick={() => {
                              setSelectedCustomer(customer);
                              setCustomerSearch('');
                            }}
                            className="w-full p-3 hover:bg-gray-50 transition text-left"
                          >
                            <div className="font-medium text-gray-800">
                              {customer.first_name} {customer.last_name}
                            </div>
                            <div className="text-sm text-gray-500">
                              {customer.email}
                              {customer.phone && ` • ${customer.phone}`}
                            </div>
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Preview */}
              <div className="bg-gray-50 p-4 rounded-lg mb-4">
                <p className="text-sm text-gray-600 mb-2">Hold tag:</p>
                <p className="font-mono font-bold text-lg text-gray-800">
                  {selectedCustomer
                    ? `${selectedCustomer.first_name} ${selectedCustomer.last_name}`
                    : generateHoldTag()}
                </p>
              </div>

              {/* Actions */}
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setShowHoldModal(false);
                    setSelectedCustomer(null);
                    setCustomerSearch('');
                  }}
                  className="flex-1 px-4 py-3 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition font-semibold"
                >
                  Cancel
                </button>
                <button
                  onClick={handleHoldOrder}
                  className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-semibold"
                >
                  Hold Order
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
